# Generated by Django 6.1.1 on 2026-09-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_flow',
            field=models.ImageField(blank=True, null=True, upload_to='projects/user_flow'),
        ),
    ]
