# Generated by Django 6.1.1 on 2026-09-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_user_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_flow',
            field=models.ImageField(blank=True, null=True, upload_to='projects/user_flow/'),
        ),
    ]
