# Generated by Django 6.1.1 on 2026-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_user_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='graduation',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
