# Generated by Django 6.1.1 on 2026-09-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile_graduation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='graduation',
            new_name='graduation_image',
        ),
    ]
