# Generated by Django 6.1.1 on 2026-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_graduation_profile_graduation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role_title',
            field=models.CharField(blank=True, default='UI/UX Designer, Full Stack Developer, Figma Designer, React Developer, Django Developer', max_length=500),
        ),
    ]
