# Generated by Django 6.1.1 on 2026-09-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_profile_role_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role_title',
            field=models.CharField(help_text='e.g. UI/UX Designer & Full Stack Developer', max_length=200),
        ),
    ]
